# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Send mail

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: create env file
        run: |
            touch .env
            echo  PASS=${{ secrets.PASS }} >> .env
            echo  EMAIL=${{ secrets.EMAIL }} >> .env
      - run: ls
      - run: npm ci
        env:
          PASS: ${{ secrets.PASS }}
          EMAIL: ${{ secrets.EMAIL }}
      - run: npm run made

